# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('city_lat', models.FloatField(default=0)),
                ('city_long', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_lat', models.FloatField(default=0)),
                ('hotel_long', models.FloatField(default=0)),
                ('adresse', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='pollsAPI.City')),
            ],
        ),
    ]
