# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollsAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('room_floor', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispo_start', models.DateField(blank=True, null=True)),
                ('dispo_end', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispo', to='pollsAPI.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoomR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserv_start', models.DateField(blank=True, null=True)),
                ('reserv_end', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserv', to='pollsAPI.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('type_desc', models.CharField(blank=True, max_length=200)),
                ('type_price', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='adresse',
        ),
        migrations.AddField(
            model_name='hotel',
            name='adr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtypes', to='pollsAPI.Hotel'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pollsAPI.RoomType'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pollsAPI.RoomType'),
        ),
    ]
