# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsAPI', '0002_auto_20170308_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='hotel',
        ),
    ]
