# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollsAPI', '0003_remove_city_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='pollsAPI.City'),
            preserve_default=False,
        ),
    ]
